

AWS_ACCESS_KEY_ID = "???"
AWS_SECRET_ACCESS_KEY = "???"

AWS_DEFAULT_REGION = "???"
env_test = "dev"

[dev-master-aaa] 
fs = "s3"
data_uri = "<bucket>/<folder>/<file>"
format = "csv"
ttl = 10


[dev-master-bbb]
fs = "s3"
data_uri = "<bucket>/<folder>/<file>"
format = "csv"
ttl = 10
